import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Slider from '../components/Slider';
import Header from '../components/Header';
import Fashion from '../components/Fashion';
import Footer from './Footer';
import Flash from '../components/Flash';
import { Cards } from '../components';
import Darazmall from '../components/Darazmall';
import Categories from '../components/Categories';
import Section from '../components/Section';

const items = [
  {
    id: 1,
    image: "https://icms-image.slatic.net/images/ims-web/52d5fa78-71ee-4174-ada6-829c46e84768.png",
    name:"Mart",
  },
  {
    id: 2,
    image: "https://icms-image.slatic.net/images/ims-web/ba5cad01-52dc-4546-82e0-8f227a6fff74.png",
    name:"Fashion",
  },
  {
    id: 3,
    image: "https://icms-image.slatic.net/images/ims-web/eeb41c48-d76c-4421-86fd-b8df8ab1a2c6.png",
    name:"Beauty",
  },
]

const Daraz = [
  {
    id: 1,
    image: "https://static-01.daraz.pk/original/24e0b7b353087cb4984257ae86450477.jpg",
    image2: "https://static-01.daraz.pk/other/shop/f4dc5c75de7ee1f397ad9aaf9bb0d23c.jpeg",
    title:"The vitamin Company",
    desc: "All Natural",
  },
  {
    id: 2,
    image: "https://static-01.daraz.pk/p/75e32a0f7b19c10cdad42e9c1e490580.jpg",
    image2: "https://static-01.daraz.pk/other/shop/893c7071913f900e482d68fe3c78aa1a.jpeg",
    title:"Boss",
    desc: "Boss",
  },
  {
    id: 3,
    image: "https://static-01.daraz.pk/p/4b4f40ee5f3446e2b8dc299831a9dd6c.jpg",
    image2: "https://static-01.daraz.pk/p/4b4f40ee5f3446e2b8dc299831a9dd6c.jpg",
    title:"Capital Entertainment",
    desc: "Capital",
  },
 { id: 4,
  image: "https://static-01.daraz.pk/p/115ac9f69f22a060af0ca2fe4191db46.jpg_200x200q75-product.jpg_.webp",
  image2: "https://static-01.daraz.pk/p/02efbf52678bbe0b484e463f0e169e32.jpg",
  title:"Burer",
  desc: "Bureur",
},
{
  id: 5,
  image: "https://static-01.daraz.pk/p/3006591b3c14c50f050339044ddfdfd9.jpg_200x200q80.jpg_.webp",
  image2: "https://static-01.daraz.pk/other/shop/77db0eff934546ffbc9fee6a5ccf4a8d.jpeg",
  title:"Good Lipstick",
  desc: "Lipstick",
},
{
  id: 6,
  image: "https://static-01.daraz.pk/p/8d266202b70f3149c4eaa6d8fa0ecb01.jpg",
  image2: "https://static-01.daraz.pk/other/shop/129e72c691fdc59a6ccc724dc3c9c56b.jpeg",
  title:"Body spray",
  desc: "Body fresher",
}
]

export default function Home() {
  return (
    <div className='bg-gray-100'>
      <Head>
    
        <title>Daraz app</title>
       
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/> 
    <Slider/> 
    <div className='grid grid-cols-2 grid-rows-2 xl:flex  lg:mx-24 xl:mx-28'>
    {items?.map((item) => (
       <Fashion {...item}/> 
    ))}

    </div>
 <Flash/>
 <div className='grid grid-cols-3 grid-rows-2 xl:flex  xl:space-x-[30px] ml-14'>
    {Daraz?.map((item) => (
       <Darazmall {...item}/> 
    ))}

    </div>
    <Categories/>
    <Section/>
    <Footer/> 
    
    {/* <Google/> */}
</div>
  )
}



